#' Check compatibility between item and REDCap data.
#'
#' This function compares patients' names
#' in the hand-written data and REDCap.
#'
#' @param d1 Item-wise data set generated by \code{import_item_data}.
#' @param d2 REDCap data set generated by \code{import_redcap_data}.
#'
#' @returns Nothing, only prints a message with data
#' discrepancies listed and stops the analysis if there
#' are any. Ought to be run within the \code{prepare_data}.
#'
#' @examples
#' \dontrun{
#' p    <- data_paths('data-raw')
#' data <- prepare_data(p)
#' }
check_compatibility <- function(d1, d2) {
  # List common variables:
  commonvars <- c(
    'sex', 'mmse', 'faq', 'faq_9', 'smoca_total', # 'vf_k', is not checked because it comes from MoCA in ItemData but from Level II in REDCap data.
    paste0('moca_', c('7', 'cube', '5words', 'anim', 'total')),
    'bdi', 'stai_1', 'stai_2', # These variables are not used in analyses directly but will likely used to describe the sample.
    NULL
  )
  # Prepare a table comparing common variables:
  tvar <-
    sapply(
      d1$id,
      function(i)
        sapply(
          commonvars,
          function(j) ifelse(
            test = !(i %in% d2$id),
            yes  = NA,
            no   = with(d1, get(j)[id == i & incl == 1]) == with(d2, get(j)[id == i])
          )
        )
    ) |>
    t()
  # Evaluate mismatches:
  tdisc <- lapply(
    set_names(commonvars),
    function(i) left_join(
      d1[d1$id %in% rownames(tvar[!tvar[ ,i], ]) & d1$incl == 1, c('id',i)],
      d2[d2$id %in% rownames(tvar[!tvar[ ,i], ])               , c('id',i)],
      by = 'id',
      suffix = c('_ItemData','_REDCap')
    )
  ) |>
    reduce(full_join, by = 'id')
  # Return mismatches as a data frame
  d1 |>
    select(id, surname, firstname, assdate) |>
    right_join(tdisc, by = 'id')
}
