#' Check compatibility between item data and REDCap data
#'
#' Compares patient names between the hand-entered item-level data and the REDCap export
#' to identify any mismatches or inconsistencies.
#'
#' @param d1 A data frame generated by \code{import_item_data}, containing item-level data.
#' @param d2 A data frame generated by \code{import_redcap_data}, containing REDCap data.
#'
#' @returns Nothing. If discrepancies are found, an informative message is printed and the
#' function stops execution (e.g., via \code{stop()}). This function is intended to be used
#' inside \code{prepare_data()} as a consistency check.
#'
#' @examples
#' \dontrun{
#' p <- data_paths("data-raw")
#' data <- prepare_data(p)  # This will internally call the compatibility check
#' }
check_compatibility <- function(d1, d2) {
  # List common variables:
  commonvars <- c(
    "sex", "mmse", "faq", "faq_9", "smoca_total", # "vf_k", is not checked because it comes from MoCA in ItemData but from Level II in REDCap data.
    paste0("moca_", c("7", "cube", "5words", "anim", "total")),
    "bdi", "stai_1", "stai_2", # These variables are not used in analyses directly but will likely used to describe the sample.
    NULL
  )
  # Prepare a table comparing common variables:
  tvar <- sapply(d1$id, function(i) {
    sapply(commonvars, function(j) {
      ifelse(
        test = !(i %in% d2$id),
        yes  = NA,
        no   = with(d1, get(j)[id == i & incl == 1]) == with(d2, get(j)[id == i])
      )
    })
  }) |>
    t()
  # Evaluate mismatches:
  tdisc <- map_dfr(set_names(commonvars), function(i) {
    left_join(
      d1[d1$id %in% rownames(tvar[!tvar[ ,i], ]) & d1$incl == 1, c("id", i)],
      d2[d2$id %in% rownames(tvar[!tvar[ ,i], ]), c("id", i)],
      by = join_by(id),
      suffix = c("_ItemData", "_REDCap")
    )
  })
  # Return mismatches as a data frame
  d1 |> select(id, surname, firstname, assdate) |>
    right_join(tdisc, by = "id")
}
