#' Check compatibility between item and REDCap data.
#'
#' This function compares patients' names
#' in the hand-written data and REDCap.
#'
#' @param d1 Item-wise data set generated by \code{import_item_data}.
#' @param d2 REDCap data set generated by \code{import_redcap_data}.
#'
#' @returns Nothing, only prints a message with data
#' discrepancies listed and stops the analysis if there
#' are any. Ought to be run within the \code{prepare_data}.
#'
#' @examples
#' \dontrun{
#' p    <- data_paths('data-raw')
#' data <- prepare_data(p)
#' }
compatibility_check <- function(d1, d2) {

  # List common variables:
  commonvars <- c(
    'sex', 'mmse', 'faq', 'faq_9', 'vf_k', 'smoca_total',
    paste0('moca_', c('7', 'cube', '5words', 'anim', 'total')),
    'bdi', 'stai_1', 'stai_2'
  )

  # Prepare a table comparing common variables:
  tvar <-
    sapply(
      d1$id,
      function(i)
        sapply(
          commonvars,
          function(j)
            with(d1, get(j)[id==i & incl==1] ) == with(d2, get(j)[id==i])
        )
    ) |>
    t()

}
