#' Compute table with demographic variables.
#'
#' This function computes demographic summaries
#' of the sample including their graphical
#' representation.
#'
#' @param d0 Data (tibble) as generated by
#' \code{prepare_data}.
#' @param vois A data.frame/tibble/matrix with variable
#' names in the first column, variable labels in the
#' second column, type of variable (continuous, binary or
#' nominal) in the third column, and optionally a fourth column
#' denoting group and a fifth column that maps each
#' label to its description in the table's note.
#' Alternatively, a path to a csv delimited by semi-colon
#' containing such a table.
#'
#' @returns A list with a tibble containing
#' raw summaries, APA-style gt table and a
#' (maybe in a future) a set of ggplots.
#'
#' @examples
#' \dontrun{
#' p    <- data_paths('data-raw')
#' data <- prepare_data(p)
#' demo <- compute_demography(data, here::here('data-raw','VariablesOfInterest.csv'))
#' }
#' @export
compute_demography <- function(d0, vois) {
  # Get variables of interest:
  if (is.character(vois)) {
    vois <- readr::read_delim(vois, delim = ';', col_types = cols())
  }
  # Prepare a demography table:
  demtab <-
    sapply(
      seq_len(nrow(vois)),
      function(i) c(
        variable = pull(vois[i, 2]),
        group    = pull(vois[i, 4]),
        N  = case_when(
          pull(vois[i, 3]) == 'binary'     ~ do_summary(d0[ , pull(vois[i, 1])], 0, 'Nperc'),
          pull(vois[i, 3]) == 'nominal'    ~ do_summary(d0[ , pull(vois[i, 1])], 0, 'Nslash'),
          pull(vois[i, 3]) == 'continuous' ~ do_summary(d0[ , pull(vois[i, 1])], 0, 'N')
        ),
        sapply(
          c('Md','minmax','M','SD'),
          function(f) ifelse(
            test = pull(vois[i, 3]) == 'continuous',
            yes  = do_summary(pull(d0[ , pull(vois[i, 1])]), ifelse(f %in% c('M','SD'), 2, 0), f),
            no   = '-'
          )
        )
      )
    ) |>
    t() |>
    as_tibble()
  # Prepare a gt table:
  gtab <-
    demtab |>
    gt_apa_table(
      grp = 'group',
      tit = '<b>Table 1</br>
      Sample description.</b> Demographic, clinical and cognitive characteristics of the sample.'
    ) |>
    cols_label(variable ~ '', minmax ~ 'Min-max')
  # If there are notes, add them to the table:
  if (ncol(vois) > 4 && any(!is.na(vois$note))) {
    notes <- vois[complete.cases(vois[ ,5]), c(2,5)]
    text  <- paste0(pull(notes[ ,1]),': ',pull(notes[ ,2])) |> paste(collapse = ', ')
    # Add the text:
    gtab <-
      gtab |>
      tab_source_note(html(paste0('<i>Note.</i> ',text)))
  }
  # Return results:
  list(table = demtab, gtable = gtab)
}
