#' Drop patients with missing data
#'
#' Drops patients with any data on PDD missing.
#'
#' @param d Data set generated by \code{diagnose_pdd_sample}
#'
#' @return The same data with less cases.
#'
#' @export
drop_incomplete <- function(d) {

  incompletes <- d |>
    dplyr::group_by(id) |>
    dplyr::summarise(drop = sum(is.na(PDD)), .groups = "drop") |>
    dplyr::filter(drop > 0) |>
    dplyr::pull(id)

  d |>
    dplyr::filter(!id %in% incompletes)

}
