#' Find patients with missing data
#'
#' Finds patients with any data on PDD missing.
#'
#' @param d Data set generated by \code{diagnose_pdd_sample}
#'
#' @return Charcter vector with incomplete cases' ids.
#'
#' @export
find_incomplete <- function(d) {
  d |>
    dplyr::group_by(id) |>
    dplyr::summarise(drop = sum(is.na(PDD)), .groups = "drop") |>
    dplyr::filter(drop > 0) |>
    dplyr::pull(id)
}
