#' Fit a grid of reference models
#'
#' Using different values of "gold standard" measures of the outcome and number
#' of expected non-zero parameters, fits a set of reference models via
#' \code{fit_reference}.
#'
#' @param d Input data, e.g., generated by \code{diagnose_pdd_sample}.
#' @param gss Gold standard variables.
#' @param N Vector of expected non-zero coefficient for a regularised horseshoe
#'   prior.
#' @param n_chosen Number of selected parameters.
#' @param bind Should all combinations of `gss` and `N` be found (`FALSE`) or
#'   should they be simply binded (`TRUE`)
#' @param ... Other parameters for [fit_reference()].
#'
#' @returns A list with four components:
#' \describe{
#'   \item{grid}{A grid of input values.}
#'   \item{reference}{List of reference models.}
#'   \item{vs_object}{List of variable selection results}
#'   \item{vs_plots}{Plots visualising variable selection}
#'   \item{projection}{List of selected models projected onto appropriate
#'   reference model}
#' }
#'
#' @seealso
#' * [fit_reference()] for reference model fitting
#' * [perform_varsel()] for variable selection implementation
#' * [projpred::project()] for projective prediction implementation
#'
#' @export
grid_models <- function(
    d,
    gss = c("Lvl.II (1)", "Lvl.II (2)"),
    N = 5,
    n_chosen = NA,
    bind = FALSE,
    ...
) {

  if (bind) {
    grid <- tibble::tibble(
      gs = gss,
      esig = N,
      n_chosen = n_chosen
    )
  } else {
    grid <- tidyr::expand_grid(
      gs = gss,
      esig = N,
      n_chosen = n_chosen
    )
  }

  refmodel <- purrr::pmap(list(grid$gs, grid$esig), function(gs, esig) {
    fit_reference(
      d = d,
      gs = gs,
      y = "PDD",
      expect_nonzero = esig,
      ...
    )
  })

  varsel <- purrr::map(refmodel, function(fit) {
    perform_varsel(
      refm_fit = fit$model,
      method = "forward",
      nclusters = 20,
      ndraws_pred = 1000
    )
  }, .progress = TRUE)

  varsel_plots <- purrr::map(varsel, function(vs) {
    rk <- projpred::ranking(vs)
    list(
      plot_pp = plot(vs, deltas = TRUE),
      plot_rk = plot(projpred::cv_proportions(rk)),
      plot_rk_cum = plot(projpred::cv_proportions(rk, cumulate = TRUE))
    )
  })

  grid <- grid |>
    dplyr::mutate(
      n_suggest = purrr::map_dbl(varsel, \(vs) projpred::suggest_size(vs)),
      n_chosen = dplyr::if_else(is.na(n_chosen), n_suggest, n_chosen)
    )

  projmodel <- purrr::pmap(list(varsel, grid$n_chosen), function(vs, n) {
    projpred::project(
      vs,
      nterms = n,
      seed = 87542,
      ndraws = 1000
    )
  })

  list(
    grid = grid,
    reference = refmodel,
    vs_object = varsel,
    vs_plots = varsel_plots,
    projection = projmodel
  )
}
