#' Prepare a list of algorithms stratified by IADL mesure
#'
#' Using the table with PDD rates estimates per diagnostic algorithm,
#' this function extracts a list of algorithms using different IADL
#' criteria for PDD. If there was an algorithm that uses both criteria
#' at the same time, the function prints an error.
#'
#' @param rates A tibble containing raw summaries of PDD rates as
#'    generated by \code{summarise_rates}.
#'
#' @returns A list with two components:
#' \describe{
#'   \item{\code{faq_tot}}{A character vector containing names of
#'   algorithms that defined IADL deficit by FAQ total score > 7.}
#'   \item{\code{faq_9}}{A character vector containing names of
#'   algorithms that defined IADL deficit by FAQ item 9 > 1.}
#' }
#'
#'@examples
#' \dontrun{
#' p <- data_paths("data-raw")
#' data <- prepare_data(p)
#' pdd  <- diagnose_pdd_sample(data)
#' vars <- here::here("data-raw", "VariablesOfInterest.csv")
#'
#' rates <- summarise_rates(pdd, vars)
#' algos <- list_algos(rates$table)
#' }
#'
#' @export
list_algos <- function(rates) {
  # List of algorithms:
  algs <- list(
    faq_tot = subset(rates, IADL == "FAQ > 7")$type,
    faq_9 = subset(rates, IADL == "FAQ 9 > 1")$type
  )
  # Sanity check:
  continue <- !(any(algs$faq_tot %in% algs$faq_9) || any(algs$faq_9 %in% algs$faq_tot))
  stopifnot("Some algorithm(s) use both IADL operationalisations!" = continue)
  # Return:
  algs
}
