#' Fit a grid of reference models
#'
#' Using different values of "gold standard" measures of the outcome and number
#' of expected non-zero parameters, fits a set of reference models via
#' \code{fit_reference}.
#'
#' @param d Input data, e.g., generated by \code{diagnose_pdd_sample}.
#' @param gss Gold standard variables.
#' @param N Vector of expected non-zero coefficient for a regularised horseshoe
#'   prior.
#' @param ... Other parameters for [fit_reference()].
#'
#' @returns A grid with columns:
#' \describe{
#'   \item{gs}{Gold standard used.}
#'   \item{esig}{Number of expected non-zero parameters.}
#'   \item{fit}{Model data as generated by \code{fit_reference}}
#' }
#'
#' @seealso [fit_reference()]
#'
#' @export
model_grid <- function(
    d,
    gss = c("Lvl.II (1)", "Lvl.II (2)"),
    N = 5,
    ...
) {

  grid <- tidyr::expand_grid(
    gs = gss,
    esig = N
  )

  grid |>
    dplyr::mutate(
      fit = purrr::pmap(list(gs, esig), function(gs, esig) {
        fit_reference(
          d = d,
          gs = gs,
          y = "PDD",
          expect_nonzero = esig
        )
      }),
      varsel = purrr::map(fit, function(fit) {
        perform_varsel(
          refm_fit = fit$model,
          method = "forward",
          nclusters = 20,
          ndraws_pred = 400
        )
      }, .progress = TRUE),
      varsel_desc = purrr::map(varsel, function(vs) {
        describe_varsel(vs)
      }),
      projection = purrr::map(varsel, function(vs) {
        perform_projpred(vs)
      })
    )
}
