#' Plot correlation matrixes
#'
#' Generates two correlation matrixes via [corrplot::corrplot()] and plots
#' them side to side. Intended to be used for visual comparison of observed
#' and "ideal" correlations as generated by \code{correlate_indexes}. Format
#' is fixed for purposes of \{demcrit\}.
#'
#' @param corrs List with correlation matrixes.
#'
#' @returns Plots the correlation matrixes from \code{corrs} side by side;
#'   with left (A) depicting observed correlations, right (B) depicting the
#'   "ideal" correlation matrix.
#'
#' @export
plot_correlation <- function(corrs) {

  draw_corr <- function(r, addCoef = FALSE){
    corrplot::corrplot(
      r,
      method = "color",
      type = "lower",
      tl.col = "black",
      tl.srt = 45,
      diag = FALSE,
      addgrid.col = "grey",
      col = corrplot::COL2("PRGn",10),
      addCoef.col = if (addCoef) "grey25" else NULL,
      number.font = 1,
      cl.lim = c(-1, 1)
    )
  }

  oldpar <- par(no.readonly = TRUE)
  on.exit(par(oldpar))

  par(
    mfrow = c(1,2),
    mar = c(1,1,2.5,1),
    oma = c(0,0,0,0)
  )

  draw_corr(corrs$R_observed, TRUE)
  mtext("A", side = 3, line = -3, adj = 0.08, font = 2, cex = 1.3)

  draw_corr(corrs$R_ideal, FALSE)
  mtext("B", side = 3, line = -3, adj = 0.08, font = 2, cex = 1.3)
}
