#' Regress PDD via Logistic Regression
#'
#' For each algorithm for probable Parkinson’s disease dementia (PDD), this
#' function fits a logistic regression model predicting the diagnosis from age,
#' sex, and their interaction. It takes as input demographic data and a tibble
#' of PDD diagnoses (typically generated via \code{diagnose_pdd_sample}).
#'
#' @param d0 A tibble of demographic data generated by \code{prepare_data}.
#' @param d1 A tibble of PDD diagnoses (typically the \code{PDD} element from
#'    the list returned by \code{diagnose_pdd_sample}).
#' @param covs Either a character vector containing covariates of interest (in
#'    which case the resulting formula will be `PDD ~ age * sex * (covariate1 + covariate2 + ...)`,
#'    or `NULL` (default case whereby the resulting formula will be `PDD ~ age * sex`).
#' @param inter A logical indicating whether covariates ought to be added to the
#'    together with their interactions with predictors of interest (default and
#'    recommended, `TRUE`) or as additive terms only (`FALSE`).
#'
#' @returns A list with the following components:
#' \describe{
#'   \item{\code{fits}}{A list of fitted logistic regression models for each PDD criterion.}
#'   \item{\code{values}}{A tibble of model coefficients and statistics.}
#'   \item{\code{plots}}{A named list of ggplot2 objects:
#'     \describe{
#'       \item{\code{data}}{Plots showing raw proportions of PDD diagnoses by age and sex.}
#'       \item{\code{parameters}}{Plots summarising effect sizes (odds ratios) and associated p-values.}
#'     }}
#' }
#'
#' @seealso
#' * [prepare_data()] prepares `d0`.
#' * [diagnose_pdd_sample()] prepares `d1`.
#' * [stats::glm()] is used to fit regressions.
#'
#' @examples
#' \dontrun{
#' p <- data_paths("data-raw")
#' data0 <- prepare_data(p)
#' data1 <- diagnose_pdd_sample(data0)
#' results <- regress_pdd_on_demographics(data0, data1$PDD)
#' }
#'
#' @export
regress_pdd_on_demographics <- function(d0, d1, covs = NULL, inter = TRUE) {
  # Extract orders for visualisation:
  ord_id <- d0 |>
    dplyr::arrange(age) |>
    dplyr::filter(!is.na(age)) |>
    dplyr::pull(id)
  ord_type <- d1 |>
    dplyr::select(PDD, type) |>
    table() |>
    prop.table() |>
    tibble::as_tibble() |>
    dplyr::filter(PDD == TRUE) |>
    dplyr::arrange(n) |>
    dplyr::pull(type)
  # Prepare further anonymisation mapping:
  anon <- dplyr::left_join(
    data.frame(id = ord_id),
    cbind.data.frame(
      id = unique(d0$id),
      sid = paste0("S", sprintf("%03d", seq_len(length(unique(d0$id)))))
    ),
    by ="id"
  )
  # Prepare data for analysis:
  df <- d1 |>
    dplyr::select(id, type, PDD) |>
    dplyr::left_join(d0, by = dplyr::join_by(id)) |>
    dplyr::mutate(
      PDD = dplyr::if_else(PDD, 1, 0),
      sid = factor(
        sapply(seq_along(id), function(i) {
          anon$sid[anon$id == id[i]]
        }),
        levels = anon$sid,
        ordered = TRUE
      ),
      type = factor(type, levels = ord_type, ordered = TRUE)
    )
  # Visualise raw data:
  plt_raw <- df |>
    dplyr::filter(!is.na(sid)) |>
    ggplot2::ggplot() +
    ggplot2::aes(x = sid, y = type, fill = factor(PDD)) +
    ggplot2::geom_tile() +
    ggplot2::scale_fill_manual(values = c("grey89", "red3"), na.value = "white") +
    ggplot2::labs(x = NULL, y = NULL) +
    ggplot2::theme(legend.position = "none") +
    ggplot2::theme(axis.text.x = ggplot2::element_text(
      angle = 90,
      vjust = .5,
      colour = dplyr::case_when(
        df$sex == "male" ~ "steelblue",
        df$sex == "female" ~ "red2"
      )
    ))
  # Prepare model formula:
  if (is.null(covs)) {
    form <- formula(PDD ~ age * sex)
  } else if (inter) {
    form <- as.formula(paste0("PDD ~ age * sex * (", paste(covs, collapse = " + "), ")"))
  } else {
    form <- as.formula(paste0("PDD ~ age * sex + ", paste(covs, collapse = " + ")))
  }
  # Get regression fits:
  fits <- lapply(rlang::set_names(unique(df$type)), function(i) {
    glm(
      formula = form,
      data = subset(df, type == i),
      family = binomial(link = "logit")
    )
  })
  # Get parameters:
  pars <- sapply(rlang::set_names(names(fits)), function(i) {
    c(or_ = exp(coefficients(fits[[i]])),
      p_ = summary(fits[[i]])$coefficients[ , "Pr(>|z|)"]
      )
  }) |>
    t()|>
    tibble::as_tibble(rownames = "type") |>
    dplyr::select(type, or_.age, or_.sexmale, `or_.age:sexmale`, p_.age, p_.sexmale, `p_.age:sexmale`) |>
    tidyr::pivot_longer(
      cols = -type,
      names_to = c("quantity", "predictor"),
      names_sep = "_",
      values_to = "estimate"
    ) |>
    dplyr::mutate(
      quantity = dplyr::case_when(
        quantity == "or" ~ "Odds Ratio",
        quantity == "p" ~ "p-value"
      ),
      predictor = factor(
        dplyr::case_when(
          predictor == ".age" ~ "Age",
          predictor == ".sexmale" ~ "Sex",
          predictor == ".age:sexmale" ~ "Age * Sex"
        ),
        levels = c("Age", "Sex", "Age * Sex"),
        ordered = TRUE
      ),
      vline_or = dplyr::if_else(quantity == "Odds Ratio", 1, NA),
      vline_p = dplyr::if_else(quantity == "p-value", .05, NA)
    )
  # Plot regression results:
  plt_regrs <- pars |>
    dplyr::filter(estimate < 20) |>
    ggplot2::ggplot() +
    ggplot2::aes(x = estimate) +
    ggplot2::geom_histogram(fill = "white", colour = "black", bins = 15) +
    ggplot2::geom_vline(ggplot2::aes(xintercept = vline_or), linetype = "dashed", linewidth = .8, colour = "blue3") +
    ggplot2::geom_vline(ggplot2::aes(xintercept = vline_p), linetype = "dashed", linewidth = .8, colour = "red3") +
    ggplot2::labs(x = NULL, y = NULL) +
    ggh4x::facet_grid2(quantity ~ predictor, scales = "free", independent = "all")
  # Return it:
  list(
    fits = fits,
    values = pars,
    plots = list(
      data = plt_raw,
      parameters = plt_regrs
    )
  )
}
