#' Summary Table of Predictors
#'
#' This helper function prepares a table showing the five best and five
#' worst-performing Level I algorithms in predicting a selected Level II-based
#' diagnosis of probable PDD. It is primarily intended for use in the manuscript
#' to keep Quarto document uncluttered.
#'
#' @param values A tibble of concordance statistics generated by
#'    \code{describe_concordance}. Can also be provided by the data [concords]
#'    propagated with the package.
#' @param struct A list generated by \code{list_algorithms} with two elements:
#' \describe{
#'   \item{`[[1]]`}{Character vector of Level I algorithm names derived using
#'   FAQ total > 7 as the IADL criterion.}
#'   \item{`[[2]]`}{Character vector of Level I algorithm names derived using
#'   FAQ item 9 > 1 as the IADL criterion. Note: order matters.}
#' }
#' @param crit A character string indicating which concordance statistics is to
#'    be used for comparisons. Can be one of `"Accuracy_raw"`, `"Balanced Accuracy"`,
#'    `"Kappa_raw"`, `"Sensitivity"` or `"Specificity"`.
#'
#' @returns A list containing:
#'   \describe{
#'     \item{\code{table}}{A tibble with the five best and five worst Level I algorithms
#'     in predicting the specified Level II-based diagnosis of probable PDD.}
#'     \item{\code{gtable}}{A \code{gt} table object summarising the concordance statistics
#'     (e.g., accuracy, kappa) of the five best and five worst Level I algorithms in predicting
#'     the specified Level II-based diagnosis of probable PDD.}
#'   }
#'
#' @seealso
#' * [concords] contains data for `values`.
#' * [describe_concordance()] prepares `values`.
#' * [list_algorithms()] prepares `struct`.
#' * [gt_apa_table()] formats the table.
#' * [psych::cohen.kappa()] computes and documents Cohen’s kappa and related metrics.
#' * [caret::confusionMatrix()] computes and documents the remaining metrics for `crit`.
#'
#' @examples
#' \dontrun{
#' p <- data_paths("data-raw")
#' data <- prepare_data(p)
#' pdd  <- diagnose_pdd_sample(data)
#' vars <- here::here("data-raw", "VariablesOfInterest.csv")
#' rates <- summarise_rates(pdd, vars)
#' algos <- list_algorithms(rates$table)
#' data(concords)
#'
#' # Tables ordered by different statistics:
#' table_levelII_approximations(concords, algos, "Accuracy_raw") # Table 3
#' table_levelII_approximations(concords, algos, "Balanced Accuracy") # Table 7
#' table_levelII_approximations(concords, algos, "Kappa_raw")
#' table_levelII_approximations(concords, algos, "Sensitivity")
#' table_levelII_approximations(concords, algos, "Specificity")
#' }
#'
#' @export
table_levelII_approximations <- function(values, struct, crit) {
  tab <- purrr::map_dfr(1:2, function(ii) {
    values |>
      dplyr::filter(reference == paste0("Lvl.II (", ii, ")")) |>
      dplyr::filter(predictor %in% struct[[ii]]) |>
      dplyr::filter(!grepl("Lvl.II", predictor)) |>
      dplyr::arrange(dplyr::desc(get(crit))) |>
      dplyr::select(reference, predictor, Kappa_raw, Accuracy_raw, AccuracyPValue, Sensitivity, Specificity) |>
      dplyr::mutate(order = seq_len(length(reference)))
  }) |>
    tidyr::pivot_wider(
      names_from = reference,
      id_cols = order,
      values_from = -c(reference, order)
    ) |>
    dplyr::mutate(
      part = dplyr::case_when(
        order %in% 1:5 ~ "Top five",
        order %in% (length(order)-4):length(order) ~ "Bottom five"
      ),
      dplyr::across(tidyselect::contains("PValue"), \(x) do_summary(x, 3, "p")),
      dplyr::across(tidyselect::where(is.numeric), \(x) do_summary(x, 2))
    ) |>
    dplyr::filter(!is.na(part)) |>
    dplyr::select(part, tidyselect::ends_with("(1)"), tidyselect::ends_with("(2)"))
  # Prepare gt table as well:
  gtab <- tab |>
    gt_apa_table(grp = "part") |>
    gt::tab_spanner(columns = tidyselect::ends_with("(1)"), label = "Level II (1)", gather = FALSE) |>
    gt::tab_spanner(columns = tidyselect::ends_with("(2)"), label = "Level II (2)", gather = FALSE) |>
    gt::cols_label(
      starts_with("predictor") ~ "Predictor",
      starts_with("Kappa") ~ "\u03BA",
      starts_with("Accuracy_") ~ "Accuracy",
      starts_with("AccuracyP") ~ "p",
      starts_with("Sensitivity") ~ "Sensitivity",
      starts_with("Specificity") ~ "Specificity"
    ) |>
    gt::tab_footnote(
      locations = gt::cells_column_spanners("Level II (1)"),
      footnote = "IADL deficit was defined as FAQ (total score) > 7"
    ) |>
    gt::tab_footnote(
      locations = gt::cells_column_spanners("Level II (2)"),
      footnote = "IADL deficit was defined as FAQ (item 9) > 1"
    ) |>
    gt::tab_source_note(
      "\u03BA: Cohen's \u03BA; p: p-value associated with a one-sided Exact Binomial Test comparing the Accuracy to
      the No Information Rate; The table shows five most accurate (Top five) and five least accurate (Bottom
      five) Level I algorithms for Parkinson's Disease Dementia (PDD) in predicting Level II classificiation
      of PDD. The algorithms were grouped by their definition of the deficit in Instrumental Activities
      of Daily Living (IADLs). The items comprising each listed algorithm can be found in Table A1."
    ) |>
    gt::opt_footnote_marks(marks = "letters")
  # Return:
  list(table = tab, gtable = gtab)
}
