#' Generate a Summary Table of Estimands
#'
#' This function creates a pre-specified table that provides a verbal summary
#' of the study's estimands for inclusion in the Appendix. It is intended as a
#' shortcut to insert a clean, structured description into a Quarto document
#' without cluttering the main text. The table content is fixed and can only be
#' modified by editing the function's code directly.
#'
#' @returns A \code{gt} table object summarising the theoretical estimands,
#'    empirical estimands, and the corresponding statistical estimates used
#'    in the study.
#'
#' @seealso [gt_apa_table()] is used to format the table.
#'
#' @export
table_estimands <- function() {
  tibble::tibble(
    RO = paste0("Research Objective ", c(rep(1,4), rep(2,1))),
    Statement = c(
      "To estimate the rate of PDD within PD.",
      "To assess variability of PDD diagnosis depending on the algorithm applied.",
      "To evaluate predictive information provided by demographic variables for probable PDD diagnosis.",
      "To evaluate the diagnostic concordance between different PDD algorithms within and between PDD criteria.",
      "To identify algorithms' components that contribute to variability in probable PDD diagnosis within and across criteria."
    ),
    Theoretical = c(
      "The true rate of PDD within the population of patients with PD.",
      "The variance of PDD rate estimates attributable to the diagnostic process itself, i.e., the extend to which different algorithms for probable PDD yield differing PDD rate estimates for the same population.",
      "The expected change of suffering with PDD given a unit change in age or sex.",
      "A set of population-level contingency tables comparing probable PDD classification assigned by each pair of probable PDD algorithms, along with derived metrics such as sensitivity, specificity, and inter-algorithm reliability coefficients.",
      "A set of algorithms' components (such as diagnostic thresholds or test indexes being used to measure a certain cognitive domain) whose variation systematically alters the probability of a probable PDD diagnosis."
    ),
    Population = c(
      "DBS candidates with PD.",
      "DBS candidates/general population of patients with PD.",
      "DBS candidates with PD.",
      "DBS candidates/general population of patients with PD.",
      "DBS candidates/general population of patients with PD."
    ),
    Empirical = c(
      "Proportion of patients classified as having probable PDD according to each of the algorithms under consideration.",
      "Shape of the distribution of probable PDD rate according to each of the algorithms under consideration.",
      "Estimates of expected change in the expected value of the probability of PDD given a change in age or sex for each of the algorithms under consideration.",
      "Matrices generated by pairwise Receiver Operating Characteristic (ROC) curve analyses that evaluate the discriminatory performance of each probable PDD algorithm.",
      "Changes in the proportion of probable PDD induced by varying sets of algorithms components."
    ),
    Estimate = c(
      "Measures of central tendency (mean, median) of the proportion of patients with probable PDD in the sample across algorithms under consideration.",
      "Measures of variability (standard deviation, range) of the proportion of patients with probable PDD in the sample across algorithms under consideration.",
      "A set of transformed logistic regression coefficients (Odds Ratios) for age, sex and their statistical interaction for each of the algorithms under consideration.",
      "Metrics derived from pairwise ROC analyses - Cohen's Kappa, Sensitivity, Specificity, Accuracy and statistical comparison between Accuracy and No Information Rate (NIR).",
      "Visually inspected differences in probable PDD rate distributions conditional on sets of algorithms' components."
    )
  ) |>
    gt_apa_table(
      grp = "RO",
      nms = "Statement"
    ) |>
    gt::tab_spanner(columns = c("Theoretical", "Population"), label = "Theoretical Estimand", gather = FALSE) |>
    gt::cols_label(
      Theoretical ~ "Quantity",
      Empirical ~ "Empirical Estimand",
      Estimate ~ "Statistical Estimate"
    )
}
