#' Prepare complete data
#'
#' Given a set o patients with incomplete PDD data, extracts data set containing
#' only complete cases. Can be applied to raw (generated by \code{prepare_data})
#' or pre-processed (generated by \code{diagnose_pdd_sample}) PDD data.
#'
#' @param d0 Data to be trimmed
#' @param inc Incomplete cases, e.g., generated by \code{find_incomplete}
#'
#' @returns The same data as input but with complete cases (regarding /PDD
#'   data) only.
#'
#' @export
trim_data <- function(d0, inc) {

  if (is.data.frame(d0)) {
    df <- d0 |>
      dplyr::filter(!id %in% inc)
  } else {
    df <- list(
      algorithms = d0$algorithms,
      PDD = d0$PDD |> dplyr::filter(!id %in% inc)
    )
  }

  df
}
